from django.db import models

class sinfo(models.Model):
    objects = models.Manager()
    NAME = models.CharField(max_length=100)
    get_id = models.CharField(max_length=100)
    PASSWORD = models.CharField(max_length=100)
    EMAIL = models.EmailField(max_length=100)
    JOB = models.CharField(max_length=100)
    SCHOOL = models.CharField(max_length=100)
    LOCATION = models.CharField(max_length=100)
    STATUS = models.CharField(max_length=100)
    INTRO = models.CharField(max_length=300)
    ENT = models.IntegerField(default = 0)
    SPT = models.IntegerField(default = 0)
    CAR = models.IntegerField(default = 0)
    TEC = models.IntegerField(default = 0)
    ECN = models.IntegerField(default = 0)
    FOOD = models.IntegerField(default = 0)
    TRIP = models.IntegerField(default = 0)
    HTH = models.IntegerField(default = 0)
    BIS = models.IntegerField(default = 0)
    FNB = models.IntegerField(default = 0)
    ANP = models.IntegerField(default = 0)
    GROW = models.IntegerField(default = 0)
    HUMOR = models.IntegerField(default = 0)
    CNM = models.IntegerField(default = 0)