# Generated by Django 3.0.8 on 2020-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('get_id', models.CharField(max_length=100)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=100)),
                ('JOB', models.CharField(max_length=100)),
                ('SCHOOL', models.CharField(max_length=100)),
                ('LOCATION', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
                ('INTRO', models.CharField(max_length=300)),
                ('ENT', models.IntegerField(default=0)),
                ('SPT', models.IntegerField(default=0)),
                ('CAR', models.IntegerField(default=0)),
                ('TEC', models.IntegerField(default=0)),
                ('ECN', models.IntegerField(default=0)),
                ('FOOD', models.IntegerField(default=0)),
                ('TRIP', models.IntegerField(default=0)),
                ('HTH', models.IntegerField(default=0)),
                ('BIS', models.IntegerField(default=0)),
                ('FNB', models.IntegerField(default=0)),
                ('ANP', models.IntegerField(default=0)),
                ('GROW', models.IntegerField(default=0)),
                ('HUMOR', models.IntegerField(default=0)),
                ('CNM', models.IntegerField(default=0)),
            ],
        ),
    ]
